CHANGES IN CORE FILE OF WORDPRESS:-
1. IN POST.PHP HAVE ADD NEW CODE FOR FLOOR PLAN DETAILS TO DO ADD UPDATE FUNCTIONALITY
2. SEARCH BY FLOOR PLAN FUNCTIONALITY , WILL FIND FLOOR PLAN FUNCTIONALITY BLOCK WHICH IS ADDED 
3. NEXT CHANGE IS DONE FOR PORPERTY ADD/UPDATE FUNCTIONALITY IN POST.PHP
4. SEARCH BY PROPERTY FUNCTIONALITY , WILL FIND ITS BLOCK 
5. CREATED DIRECTORY IN /wp-content/uploads/ PATH NAMED imagereality_images i.e wp-content/uploads/imagereality_images OF ALL IMAGES REALTED TO IMAGE REALITY UPLOADS
   AND MORE DIRECTORIES RELATED TO CUSTOM PLUGINS ARE AS FOLLOWS:-
   I. IN fLOOR PLAN DETAILS IT IS UPLOADS IN DIRECTORY NAMED floor_plans i.e wp-content/uploads/imagereality_images/floor_plans 